<?php

function wypiszemy($tab,$sciezka)
	{
	for($i=0;$i<count($tab);$i++)
		{
			echo'<a href="'.$sciezka.$tab[$i].'.php" >&lt'.$tab[$i].'&gt</a><br/>';
		}
	}
$znacznik=array(76);
$znacznik[0]='a';
$znacznik[1]='abbr';
$znacznik[2]='acronym';
$znacznik[3]='address';
$znacznik[4]='area';
$znacznik[5]='b';
$znacznik[6]='base';
$znacznik[7]='bdo';
$znacznik[8]='big';
$znacznik[9]='blockquote';
$znacznik[10]='body';
$znacznik[11]='br';
$znacznik[12]='button';
$znacznik[13]='caption';
$znacznik[14]='cite';
$znacznik[15]='code';
$znacznik[16]='col';
$znacznik[17]='colgroup';
$znacznik[18]='dd';
$znacznik[19]='del';
$znacznik[20]='dfn';
$znacznik[21]='div';
$znacznik[22]='dl';
$znacznik[23]='dt';
$znacznik[24]='em';
$znacznik[25]='fieldset';
$znacznik[26]='form';
$znacznik[27]='h1';
$znacznik[28]='h2';
$znacznik[29]='h3';
$znacznik[30]='h4';
$znacznik[31]='h5';
$znacznik[32]='head';
$znacznik[33]='hr';
$znacznik[34]='html';
$znacznik[35]='i';
$znacznik[36]='imp';
$znacznik[37]='input';
$znacznik[38]='ins';
$znacznik[39]='kbd';
$znacznik[40]='label';
$znacznik[41]='legend';
$znacznik[42]='li';
$znacznik[43]='link';
$znacznik[44]='map';
$znacznik[45]='meta';
$znacznik[46]='noscript';
$znacznik[47]='object';
$znacznik[48]='ol';
$znacznik[49]='optgroup';
$znacznik[50]='option';
$znacznik[51]='p';
$znacznik[52]='param';
$znacznik[53]='pre';
$znacznik[54]='q';
$znacznik[55]='samp';
$znacznik[56]='script';
$znacznik[57]='select';
$znacznik[58]='small';
$znacznik[59]='span';
$znacznik[60]='strong';
$znacznik[61]='style';
$znacznik[62]='sub';
$znacznik[63]='sup';
$znacznik[64]='table';
$znacznik[65]='tbody';
$znacznik[66]='td';
$znacznik[67]='textarea';
$znacznik[68]='tfoot';
$znacznik[69]='th';
$znacznik[70]='thead';
$znacznik[71]='title';
$znacznik[72]='tr';
$znacznik[73]='tt';
$znacznik[74]='ul';
$znacznik[75]='var';

?>